title: Yotam Aflalo
logo: /assets/img/headshot_circle.png
description: Data Scientist with a strong academic foundation and diverse professional experience.
show_downloads: true
theme: jekyll-theme-minimal
